### ISSUE TITLE
Vignette doesn't work

### ISSUE THREAD

**Issue by sztach** [ModelOriented/ingredients#23] opened 2019-06-04 09:39 UTC
When I try to open a vignette from RStudio, it returns an error with description that it wasn't able to find any vignettes.

**Comment by sztach** [comment] 2019-06-04 09:50
It doesn't work even after adding vignettebuilder to the description of the package.

**Comment by pbiecek** [comment] 2019-06-04 11:24
Thanks, could you give more details?
What error? Would you put here an reproducible example?

**Comment by sztach** [comment] 2019-06-04 11:37
By error I meant that RStudio couldn't find a vignette even if it exists in the correct folder. So if you load the package and then type vignette(package = 'ingredients') it should show the vignette with titanic data, but apparently it's not the case.

**Comment by pbiecek** [comment] 2019-07-07 17:55
@sztach is it still an issue?

**Comment by sztach** [comment] 2019-07-09 11:49
Yes, it is. I have reinstalled ingredients package with command _devtools::install_github("ModelOriented/ingredients", build_vignettes=TRUE)_
After that I loaded the package and ran command _vignette(package = 'ingredients')_, but no vignettes were found.

**Comment by pbiecek** [comment] 2019-09-23 20:14
Not sure how to solve this.
But since vignettes are in the pkgdown website, I will close this issue

**Closed as completed by pbiecek** 2019-09-23 20:14 UTC
